### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by isamu68** [amisadmin/fastapi_amis_admin_demo#14]
I am trying to run this demo on python 3.8.0. but I got an error as follows,

PS C:\DevOps\Python\Fastapi\fastapi-amis-admin-demo> python -m pdm run run
Traceback (most recent call last):
  File "C:\Users\ykaku\.pyenv\pyenv-win\versions\3.8.0\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ykaku\.pyenv\pyenv-win\versions\3.8.0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\DevOps\Python\Fastapi\fastapi-amis-admin-demo\.venv\Scripts\uvicorn.exe\__main__.py", line 7, in <module>
  File "C:\DevOps\Python\Fastapi\fastapi-amis-admin-demo\.venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\DevOps\Python\Fastapi\fastapi-amis-admin-demo\.venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\DevOps\Python\Fastapi\fastapi-amis-admin-demo\.venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\DevOps\Python\Fastapi\fastapi-amis-admin-demo\.venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\DevOps\Python\Fastapi\fastapi-amis-admin-demo\.venv\lib\site-packages\uvicorn\main.py", line 403, in main
    run(
  File "C:\DevOps\Python\Fastapi\fastapi-amis-admin-demo\.venv\lib\site-packages\uvicorn\main.py", line 568, in run
    server.run()
  File "C:\DevOps\Python\Fastapi\fastapi-amis-admin-demo\.venv\lib\site-packages\uvicorn\server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\ykaku\.pyenv\pyenv-win\versions\3.8.0\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\ykaku\.pyenv\pyenv-win\versions\3.8.0\lib\asyncio\base_events.py", line 608, in run_until_complete
    return future.result()
  File "C:\DevOps\Python\Fastapi\fastapi-amis-admin-demo\.venv\lib\site-packages\uvicorn\server.py", line 66, in serve
    config.load()
  File "C:\DevOps\Python\Fastapi\fastapi-amis-admin-demo\.venv\lib\site-packages\uvicorn\config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\DevOps\Python\Fastapi\fastapi-amis-admin-demo\.venv\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\ykaku\.pyenv\pyenv-win\versions\3.8.0\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\DevOps\Python\Fastapi\fastapi-amis-admin-demo\backend\main.py", line 1, in <module>
    from core.globals import site
  File "C:\DevOps\Python\Fastapi\fastapi-amis-admin-demo\backend\core\globals.py", line 11, in <module>
    sync_db = Database.create(
  File "C:\DevOps\Python\Fastapi\fastapi-amis-admin-demo\.venv\lib\site-packages\sqlalchemy_database\database.py", line 227, in create
    engine = create_engine(url, **kwargs)
  File "C:\DevOps\Python\Fastapi\fastapi-amis-admin-demo\.venv\lib\site-packages\sqlalchemy\future\engine.py", line 21, in create_engine
    return _create_engine(*arg, **kw)
  File "<string>", line 2, in create_engine
  File "C:\DevOps\Python\Fastapi\fastapi-amis-admin-demo\.venv\lib\site-packages\sqlalchemy\util\deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "C:\DevOps\Python\Fastapi\fastapi-amis-admin-demo\.venv\lib\site-packages\sqlalchemy\engine\create.py", line 518, in create_engine
    u = _url.make_url(url)
  File "C:\DevOps\Python\Fastapi\fastapi-amis-admin-demo\.venv\lib\site-packages\sqlalchemy\engine\url.py", line 725, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "C:\DevOps\Python\Fastapi\fastapi-amis-admin-demo\.venv\lib\site-packages\sqlalchemy\engine\url.py", line 786, in _parse_rfc1738_args
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string ''

here is the package installed. is there any version issue?

Synchronizing working set with resolved packages: 61 to add, 0 to update, 0 to remove

  ✔ Install setuptools 65.4.0 successful
  ✔ Install cfgv 3.3.1 successful
  ✔ Install aiofiles 22.1.0 successful
  ✔ Install aiosqlite 0.17.0 successful
  ✔ Install binaryornot 0.4.4 successful
  ✔ Install colorama 0.4.5 successful
  ✔ Install certifi 2023.7.22 successful
  ✔ Install click 8.1.3 successful
  ✔ Install arrow 1.3.0 successful
  ✔ Install alembic 1.7.7 successful
  ✔ Install anyio 3.7.1 successful
  ✔ Install exceptiongroup 1.1.3 successful
  ✔ Install charset-normalizer 3.3.2 successful
  ✔ Install distlib 0.3.6 successful
  ✔ Install cookiecutter 2.4.0 successful
  ✔ Install filelock 3.8.0 successful
  ✔ Install chardet 5.2.0 successful
  ✔ Install h11 0.14.0 successful
  ✔ Install identify 2.5.5 successful
  ✔ Install idna 3.4 successful
  ✔ Install importlib-metadata 4.12.0 successful
  ✔ Install fastapi 0.104.1 successful
  ✔ Install greenlet 1.1.3 successful
  ✔ Install fastapi-amis-admin 0.6.7 successful
  ✔ Install fastapi-amis-admin-cli 0.2.0 successful
  ✔ Install importlib-resources 5.9.0 successful
  ✔ Install markupsafe 2.1.1 successful
  ✔ Install jinja2 3.1.2 successful
  ✔ Install mdurl 0.1.2 successful
  ✔ Install nodeenv 1.7.0 successful
  ✔ Install mako 1.2.3 successful
  ✔ Install platformdirs 2.5.2 successful
  ✔ Install python-dotenv 0.21.0 successful
  ✔ Install python-slugify 8.0.1 successful
  ✔ Install markdown-it-py 3.0.0 successful
  ✔ Install python-dateutil 2.8.2 successful
  ✔ Install pyyaml 6.0 successful
  ✔ Install six 1.16.0 successful
  ✔ Install requests 2.31.0 successful
  ✔ Install pre-commit 2.20.0 successful
  ✔ Install psutil 5.9.6 successful
  ✔ Install sniffio 1.3.0 successful
  ✔ Install sqlmodel 0.0.8 successful
  ✔ Install sqlmodelx 0.0.5 successful
  ✔ Install rich 13.6.0 successful
  ✔ Install text-unidecode 1.3 successful
  ✔ Install toml 0.10.2 successful
  ✔ Install starlette 0.27.0 successful
  ✔ Install typer 0.9.0 successful
  ✔ Install types-python-dateutil 2.8.19.14 successful
  ✔ Install sqlalchemy2-stubs 0.0.2a34 successful
  ✔ Install zipp 3.8.1 successful
  ✔ Install sqlalchemy 1.4.41 successful
  ✔ Install uvicorn 0.21.1 successful
  ✔ Install python-multipart 0.0.5 successful
  ✔ Install urllib3 2.0.7 successful
  ✔ Install pydantic 1.10.13 successful
  ✔ Install pygments 2.16.1 successful
  ✔ Install virtualenv 20.16.5 successful

🎉 All complete!

**Comment by isamu68** [comment]
resolved it. define     database_url: str = "sqlite:///amisadmin.db" in setting.py
